name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build-landing-page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build landing page
        run: docker build -t stekoe/spring-boot-app:landing .

      - name: Push landing page
        run: docker push stekoe/spring-boot-app:landing
